version: '3.8'

services:
  o2o-fe:
    container_name: o2o-fe
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_MOCKING=${NEXT_PUBLIC_API_MOCKING}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_KAKAO_APP_KEY=${NEXT_PUBLIC_KAKAO_APP_KEY}
        - NEXT_PUBLIC_PAY200_KEY=${NEXT_PUBLIC_PAY200_KEY}
        - NEXT_PUBLIC_TOSS_PAY_KEY=${NEXT_PUBLIC_TOSS_PAY_KEY}
    image: yong7317/o2o-fe:latest
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_MOCKING=${NEXT_PUBLIC_API_MOCKING}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_KAKAO_APP_KEY=${NEXT_PUBLIC_KAKAO_APP_KEY}
      - NEXT_PUBLIC_PAY200_KEY=${NEXT_PUBLIC_PAY200_KEY}
      - NEXT_PUBLIC_TOSS_PAY_KEY=${NEXT_PUBLIC_TOSS_PAY_KEY}
    networks:
      - o2o-network

networks:
  o2o-network:
    driver: bridge
