export const ROUTE_PATHS = {
  WELCOME: '/',
  HOME: '/home',
  HOME_LIST: '/home/list',
  SEARCH: '/search',
  SEARCH_RESULT: '/search/result',
  FAVORITES: '/favorites',
  ORDERS: '/orders',
  ORDERS_DETAIL: '/orders/detail',
  PAY: '/pay',
  MYPAGE: '/mypage',
  STORE_DETAIL: '/store/detail',
  MYPAGE_EDIT_PROFILE: '/mypage/edit-profile',
  REVIEW: '/reviews',
}
