name: Deploy Develop Client to Docker Hub

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  client-build:
    uses: ./.github/workflows/develop-deploy-v1.yml
    name: "Build and Deploy for Develop Client"
    secrets: inherit