name: Deploy Main Client to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  client-build:
    uses: ./.github/workflows/main-deploy-v1.yml
    name: "Build and Deploy for Main Client"
    secrets: inherit