on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 환경 변수 파일 생성
      - name: 환경 변수 설정
        run: |
          echo "${{ secrets.ENV_PROPERTIES }}" > .env
          cat .env # 환경 변수 파일이 제대로 생성되었는지 확인 (민감한 정보는 로그에서 마스킹됨)

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # Docker 이미지 빌드 및 태깅
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yong7317/o2o-fe:latest
          build-args: |
            ENV_CONTENT=${{ secrets.ENV_PROPERTIES }}

      # EC2 도커 컴포즈 실행
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd frontend
            docker stop o2o-fe || true
            docker rm o2o-fe || true
            docker pull yong7317/o2o-fe:latest
            docker-compose up -d
